//! Raw Camera2 NDK sys bindings for Android.
//!
//! This crate is generated by `bindgen` against the Android NDK headers at
//! build time (requires `ANDROID_NDK_ROOT` and the `bindgen` feature).
//! It is only meaningful when targeting `aarch64-linux-android` or similar.
//!
//! Consumers should prefer the safe wrappers in `rcam::backend::android`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

// Include generated bindings when targeting Android.
#[cfg(all(target_os = "android", feature = "bindgen"))]
include!(concat!(env!("OUT_DIR"), "/camera2_bindings.rs"));
